# (4). diag() ==== 

In [3]:
# (4). diag() ==== 
import numpy as np

In [4]:
a = np.diag([1,45,78,90])
a

array([[ 1,  0,  0,  0],
       [ 0, 45,  0,  0],
       [ 0,  0, 78,  0],
       [ 0,  0,  0, 90]])

# (5). Random Module ===> 

In [3]:

# (a). Randint() ===> np.random.randint(min_number , max_number , total_numbers)
# (b). Rand() ====> 0-1 random numbers . 
# (c). randn() ===> -3 to +3 . 
# (d). seed() ===> fix our random numbers . 

#  Randint() Function

(a). Randint() ===> np.random.randint(min_number , max_number , total_numbers)

In [15]:
a=np.random.randint(1,10,3)
a

array([4, 7, 2])

# Rand() Function

### 0-1 random numbers

In [9]:
a = np.random.rand(3)
a

array([0.27918309, 0.42064025, 0.10277051])

#  randn() Function

##  -3 to +3 Start

In [8]:
a = np.random.randn(3)
a

array([-0.01807969,  0.24226407,  0.26321143])

# seed () Function

fix our random numbers 

In [14]:
np.random.seed(45)

a = np.random.randint(1,10,3)
a

array([4, 1, 6])

# # matrix ===> reshape ===> 

row* column = total_elements

In [16]:
a = np.random.randint(1,59,12)
a

array([47,  9, 54, 13, 35, 25, 13, 18, 39,  5, 47, 31])

In [17]:
a.reshape(2,6)

array([[47,  9, 54, 13, 35, 25],
       [13, 18, 39,  5, 47, 31]])

In [20]:
a.reshape(6,2)

array([[47,  9],
       [54, 13],
       [35, 25],
       [13, 18],
       [39,  5],
       [47, 31]])

In [21]:
a.reshape(3,4)

array([[47,  9, 54, 13],
       [35, 25, 13, 18],
       [39,  5, 47, 31]])

In [22]:
a.reshape(4,3)

array([[47,  9, 54],
       [13, 35, 25],
       [13, 18, 39],
       [ 5, 47, 31]])

cannot reshape array of size 12 into shape (5,6)# 

In [23]:
a.reshape(5,6)

ValueError: cannot reshape array of size 12 into shape (5,6)

# View vs Copy()

In [25]:
a = np.array([10,20,30,40,50,60,70,80])
b=a[3:6]
b[:]= 0
a

array([10, 20, 30,  0,  0,  0, 70, 80])

In [27]:
a = np.array([10,20,30,40,50,60,70,80])
b=a[3:6].copy()
b[:]= 0
b
a

array([0, 0, 0])

# LinSpace()

same gap values

In [32]:
 a = np.linspace(1,2,5)
a

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

# Unique()

In [33]:
a = np.array([10,20,30,10,10,10,10,40,50])
np.unique(a , return_index = True , return_counts = True)

(array([10, 20, 30, 40, 50]),
 array([0, 1, 2, 7, 8], dtype=int64),
 array([5, 1, 1, 1, 1], dtype=int64))

# Conditional Selection in Numpy 

In [4]:
import numpy as np
a = np.arange(1,16,1)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [5]:
a>10

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True,  True])

In [6]:
b = a>10 
a[b]

array([11, 12, 13, 14, 15])

In [7]:
a[a%2 == 0] 

array([ 2,  4,  6,  8, 10, 12, 14])

# Matrix Add(+)

In [8]:
a = np.arange(1,5).reshape(2,2)
a

array([[1, 2],
       [3, 4]])

In [12]:
b = np.arange(5,9).reshape(2,2)
b

array([[5, 6],
       [7, 8]])

In [13]:
a+b  ## 1+5 = 6 , 2+6 = 8 , 3+7 = 10 , 4+8 = 12 

array([[10, 12],
       [14, 16]])

# Matrix sub(-)

In [14]:
a-b

array([[0, 0],
       [0, 0]])

# matrix multiplication (*)

In [15]:
a.dot(b)

array([[ 67,  78],
       [ 91, 106]])

# Stacking

## (a). hstack() ===> horizontally adds 2 or more arrays . 
## (b). vstack() ====> vertically adds 2 or more arrays . 

In [16]:
## (a). hstack() ===> horizontally adds 2 or more arrays 
. 
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
c = np.array([9,10,11,12])
np.hstack((a,b,c))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [17]:
#vstack() ====> vertically adds 2 or more arrays .
np.vstack((a,b,c))


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

# ---------------------------------end------------------------------------------------